package com.terra.framework.nova.service;

import org.springframework.ai.document.Document;

import java.util.List;

/**
 * Service interface for Retrieval-Augmented Generation (RAG) operations.
 */
public interface RagService {

    /**
     * Loads a list of documents into the vector store.
     * This involves splitting text, embedding, and storing the documents.
     *
     * @param documents The documents to load.
     */
    void load(List<Document> documents);

    /**
     * Asks a question to the RAG system.
     * The system will find relevant documents from the vector store,
     * augment the prompt with this context, and then ask the chat model
     * to generate an answer.
     *
     * @param query The user's question.
     * @return The answer generated by the language model.
     */
    String ask(String query);

    /**
     * Deletes all documents from the vector store.
     * Use with caution.
     */
    void deleteAll();
} 